# Generated by Django 5.2.1 on 2025-05-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVITE_ONLY', 'Invite Only'), ('FULL', 'Full')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
