# Generated by Django 5.2.1 on 2025-05-25 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_rooms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='studyroom',
            name='tech_enhanced',
        ),
        migrations.AlterField(
            model_name='studyroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyroom',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('study_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='study_rooms.studyroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
